(function (cjs, an) {

var p; // shortcut to reference prototypes
var lib={};var ss={};var img={};
lib.ssMetadata = [
		{name:"Nack_newhaiku_atlas_1", frames: [[0,0,1228,104]]}
];


(lib.AnMovieClip = function(){
	this.actionFrames = [];
	this.ignorePause = false;
	this.gotoAndPlay = function(positionOrLabel){
		cjs.MovieClip.prototype.gotoAndPlay.call(this,positionOrLabel);
	}
	this.play = function(){
		cjs.MovieClip.prototype.play.call(this);
	}
	this.gotoAndStop = function(positionOrLabel){
		cjs.MovieClip.prototype.gotoAndStop.call(this,positionOrLabel);
	}
	this.stop = function(){
		cjs.MovieClip.prototype.stop.call(this);
	}
}).prototype = p = new cjs.MovieClip();
// symbols:



(lib.CachedBmp_1 = function() {
	this.initialize(ss["Nack_newhaiku_atlas_1"]);
	this.gotoAndStop(0);
}).prototype = p = new cjs.Sprite();



(lib.Goldmedal = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// sparkle
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgVBQIgVgBQgLgBgJgEQgLgGgGgNQgGgNACgMQACgKAHgSQABgGAAgXQgBgTAGgKQAMgVAsgCQAZgCAQADQAXADAOANQAOAOADAYQADARgCAaQgCApgSAMQgLAIgaAAg");
	this.shape.setTransform(46.59,-0.2944);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgTC1QgLgGgGgLQgIgOAAgdIACg9IgHAAQg9AAgdgIQgigKgGgWQgEgOAJgNQAIgMAOgGQATgJAnACIAxAAQgCgSgEgPIgHgdQgFgRgBgMQgDglAWgSQALgJARABQAQABAHAMIAGAQQADAJAEAEQAEAGANAGQANAIAFAUQADAMAAAXIAAAhIALgBIAogCQAXAAAQAHQATAIAKATQAKASgIASQgIARgWAGQgQAFgbABIgwAAIAAAuQAAAqgMASQgPAWgaAAQgMgBgLgGg");
	this.shape_1.setTransform(44.3969,-2.1548);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgyDiQgQgFgIgNQgGgMAAgQQAAgLAEgTIAGgfQgYARgZgCQgRgBgPgLQgPgMgCgQQgCgVAQgUIALgLQgtABgsgCQgWgBgLgGQgJgGgFgJQgGgKABgKQABgLAHgJQAHgJAKgEQAOgFADgCQADgCACgGIAEgJQAKgUAqgBIApAAIgJgKQgYgbACgdQABgQAMgMQAMgMAPABQASAAAYAbIAoAtIAAgVIABgiQACgUAHgNQAJgQAQgHQARgIAOAIQAWANABAuIAAArIAXgYQAYgWAYgHQAbgKASANQANAIADASQADARgHAPQgFALgNAOIBPAAQAYAAAMAGQASAKABAUQADAUgQANQgJAIgXAFQhNARhKALQAiAZAhAQQAZAMAKAIQASAOABARQABARgPANQgPAMgSAAQgQAAgSgHQgMgGgTgLQgpgZghgZQgFAogIApQgJAwgWAMQgIAFgJAAQgGAAgGgCg");
	this.shape_2.setTransform(44.1097,2.613);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AgDCcQgUgIgHgTIgFgSQgCgMgEgGQgDgFgJgHIgJgIIgSgBQg4gDgZgRQgSgMgHgVQgIgVAKgRQALgUAdgHQARgDAhADIATACQABgpAGgTQAFgSALgNQAMgOAPgGQAQgFAPAEQARAEALALQASATACAjQABALgBASIgBAUIAtAAQAnAAAQAFQAOAFAKAKQALAKACAMQADAPgJAPQgJAOgOAIQgVAMgpACIgiACIABARQgBAVgHARQgIATgQAIQgKAFgKAAQgJAAgIgDg");
	this.shape_3.setTransform(43.6744,0.4986);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AgDCcQgUgIgHgTIgEgQIgIgJQgEgFgEgJIgEgKIgIgHIgSgBQg4gDgZgRQgSgMgHgVQgIgVAKgRQALgUAdgHQARgDAhADIATACQABgpAGgTQAFgSALgNQAMgOAPgGQAQgFAPAEQARAEALALQASATACAjQABAJgBAPIADABQAUAHAPARIAGAAQAnAAAQAFQAOAFAKAKQALAKACAMQADAPgJAPQgJAOgOAIQgSAKghADIgDADQgDAEgJAGIgMAJIgJAOQgGAJgEAEIgEAEIgCAFQgIATgQAIQgKAFgKAAQgJAAgIgDg");
	this.shape_4.setTransform(43.6744,0.4986);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AgtBWQgegMgUgbQgUgbgDgfQgEgmAWgXQAVgWAygBQAqAAAsAJQAfAHALAPQAGAJADANIADAZIAFAXIAEAYQACAdgOASQgKALgTAEQgMADgWABIgSAAQguAAgagKg");
	this.shape_5.setTransform(43.9439,3.2385);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[]}).to({state:[{t:this.shape}]},4).to({state:[{t:this.shape_1}]},4).to({state:[{t:this.shape_2}]},4).to({state:[{t:this.shape_3}]},4).to({state:[{t:this.shape_4}]},4).to({state:[{t:this.shape_5}]},4).wait(4));

	// gold
	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f().s("#000000").ss(5,1,1).p("AM1AAQAAFUjxDwQjwDxlUAAQlTAAjxjxQjwjwAAlUQAAlTDwjxQDxjwFTAAQFUAADwDwQDxDxAAFTg");
	this.shape_6.setTransform(-1.95,0);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFF00").s().p("ApEJEQjvjwAAlUQAAlTDvjxQDxjwFTAAQFUAADwDwQDxDxgBFTQABFUjxDwQjwDxlUAAQlTAAjxjxg");
	this.shape_7.setTransform(-1.95,0);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_7},{t:this.shape_6}]}).wait(28));

	// ribon
	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#3300FF").s().p("AqOdCQgjgZgWgwQgPgegRg8QjTrjhOl9QiCpzALoBQAEizAcknQARiyAQhZQA4lFCuiAQBehFCdgdQBSgPBngGQBDgDB3gBQDagCB/AHQC+AKCYAgQCdAiBhA8QCXBdBeDCQAmBOAdBkQAWBNAWBtQCGKShCKsQhCKlj/J1QgXA5gSAeQgbAugiAaQgjAagsAGQgtAHgogRQgogQgZglIgHgKQgrARgygPQg8gSgbgzQgag0AOhIQAKguAihPQB+klBRk0QAoiXANhsQAIg/ADhPQACgvABhfQADkEAAoLQAAhpgCg4QgEhagNhHQgqjjiajPQgxhDgugiQhFgzh4gVQjGghjnA4IgNAGQgyAXgYANQgqAWgYAZQgSATgbAsQgxBSgVAoQglBGgSA8IgDAKQgIBYgDAzQgIB1AGBdQAHCJAyDoQA5EJANBmQAEAkAOC5QALCIARBUQAQBOAuCJQAxCUAQBDQAuDFgWDIQgGA3gNAlQgQAwgfAdQgbAZgkAJIgIACIAZBPQAYBNAEAvQAGBFgeAwQgfAxg/AMQgQAEgPAAQgsAAgjgag");
	this.shape_8.setTransform(5.0811,-192.1924);

	this.timeline.addTween(cjs.Tween.get(this.shape_8).wait(28));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-110.2,-380.5,230.60000000000002,465.1);


(lib.Food = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Sparks
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFF00").s().p("Eg4UAq1QgagVgIggIAAgHIAAgIIgCgHIABgIIABgHIAAgIIAAgHIADgIQAJgXAMgWQAUgpAXgoIALgQIADgIIABgHIABgIIAFgIQAqhXBDhHQAsguAwgqIALgJQAVgQAYgLIALgCQCBgaBNBoQAQAVAUAQIACgDQADgHACgIIAEgPIADgWIABgIIAFgIIADgHIABgHIABgIIAGgHQASgdARgfQAhg8AxgtQABgEACgDQBAhKBJhDQA6g2BIgkIAKgCQCPgiBEB4QAPAaALAcIACgBIADgHIABgHIAAgIIABgIIABgOIACgIIADgHIACgIIAAgHIABgIIABgIIABgHIAAgHIADgIIACgHIACgIIAAgHIABgIIABgIIABgHIAAgHIADgIIACgHIADgIIAEgIIADgHIAFgHIAAgIIAAgHIACgIQADgMAGgLQAKgSALgRQANgTAKgUIAIgIIAHgHIAPgQIAPgPIAPgHQAXgLAXgJQAbgKAbgIIAUgBIAAgBQCZAACYAGQBSADAeBKIACAHIABAIIABAHIACAIIgCAHIgCAHIgBAIIgBAIIgEAHIgEAHIgEAIIgFAIIgFAHIgHAHQgbAVgiABQgbAAgWgOIj2gCIgEACIgKADQgQAGgOAHIgNAHIgGAHIgGAIIgFAHIgDAHIgFAIIgBAHIgBAIIgDAHIgFAIIgDAHIgFAIIAAAIIAAAHIAAAIIAAAHIgCAPIAAAIIgCAHIgDAIIgDAHIAAAIIAAAHIgBAIIgBAHIAAAIIgCAHIgDAIIgDAHIAAAIIAAAHIgBAIIgBAHIAAAIIgDAHIgDAHIgDAIIgEAHIgEAIIgCAIIgBAHIAAAIIgDAHIgCAIIgCAPIgDAPIgDAPIgEAHIgDAIIgCAHIgBAIIgEAHIgUAuQgXA2g0AZIgKACQhcARgqhQIguhbIgCgIIgBgHIgFgIIgDgHIgHgPIgIgPIgFgIIAAgHIgCgIIgDgHIgFgIIAAgHIgCgIIgCgHIgKABQgIACgIAEIgMAIIgGAGQgxAmgrAtQgtAwgqAyIgDAHIgNAWQgMATgKATIgTAmIgDAIIAAAHIAAAIIgDAHIgCAIIgCAHIAAAIIAAAHIAAAIIAAAHIAAAIIAAAHIACAIIACAHIADAIIADAHIAEAPIADAIIABAHIABAPIABAXQAAATgCASIgBAIIgDAHIgKAWQgKATgSALIgVANQgGACgFgBQiMgThmhxQgngrgmguIgNgFIgIAHIgMAIIgMAIIgFAHIgEAHIgEAIIgIAIIgHAHIgIAIIgIAHIgCAHIgFAIIgFAHIgHAIIgIAIIgEAHQgiA7gfA+QgbA5ggA2QgGAIgHAHIgJAIQgLAKgOAFIgKADQgLACgKAAQggAAgagWgEA2YAiPQgagdgSgkIgCgPIgEgPIgGgXIgIgWQgNAAgMABIgPADIgUAGQjZBvjwg3QgPgEgLgMIgPgPIgIgPIgEgIIgDgHIgIgPQgHhDABhEIAEi0IAAgeIACgIIADgHIADgIIAAglQgBgeABgeQABgWgEgVIgDgBQgNgCgOAAQiZAciJBHQgPAHgPAFQhHAqhOAfQgsASgqAVQhfAehDg/IgXgWIgEgIIgEgHIgEgHIgDgPIgCgQIgBgOIAAgPIgCgIIgCgHIgDgIIgBgeQgBgTAAgTIAAglIgDgIIgDgHIgCgIQgDgaABgaIAAhTIAAglIgDgIIgDgHIgCgIIAAgHIAAgHIgCgIIAAgIIAAgHQgGgKgCgNQgBgLgEgKQgEgQgBgPIgKgPIgFgIIgKgPIgCgHIgCgIIgBgHIgBgIIgCgHIACgIIABgHIAAgIQACgMAIgLQAKgQAQgMQAMgKAOgGIALgCIAUgCIAAgBQAlgBAdAYQAeAYAOAjIABAIIABAHIAFAIIACAHIACAIIABAHIAFAIIACAHIADAPIADAPIACAPIAFAPQAGAmADAmQADA4ABA4IAAAlIACAIIADAHIACAIQgBAMACALQABAOAAAPIAAAtIADADQAIABAHgBQCGg/CIg4QA2gWA2gYQCZgzCYAoQAaAHATAVIAWAXIAMAXIAJAWIAKAeQACAlAAAmIgBB4IgBAmIgDAHIgDAIIgCAHIAAA8IAABiIAAAqIBYAAQAdgOAegJQAVgGAUgLQCSg8CZAMQAXACASATIAbA0QAVArAQAvQAEAPABAPIAGAIIAEAHIAEAHIAEAIIAAAIIACAHIABAIIACAHIAAAIIAAAHIgCAIIAAAHIAAAIQgEAMgEALQgJARgOAMQgPAMgRAIQgPAFgOAAQgmAAgdgggA7+zWQgRgLgPgPIgFgIIgDgHIgFgIIAAgHIgCgIIgDgHIgFgIIgCgPIgBgWIgBgmIAAgeQgLgjAAgoIABiOIAAhLQhCAZg4AwQg6A0g4A3QgqAfgxAMQhIARgsg8IgEgIIgEgHIgFgIIAAgHIgCgPIgCgPIgBgXIAAgHIgCgIIgCgHIgDgIIAAgHIAAgIIgCgHIgBgIIAAgHIAAgIIgBgHIgDgPIgDgPIgFgXIgFgPIAAgHIAAgIIgDgHIgEgIIgBgHIgCgIIgDgPIgCgPIgFgPIAAgHIAAgIIgDgHIgFgIIAAgHIgCgIIgCgPIgEgPIgEgPIAAgHIAAgIIgCgHIAAgIIgEgHIgDgIIgEgHIgFgIIAAgHIgBgIIgBgHIgDgIIgEgPIgDgHIAAgIIAAgHIgFgIIgCgHIgCgIIgBgHIgFgIIgDgHIgEgIIgDgHIgCgIIgDgHIgBgIIgCgPIgFgWQgDgUgHgSIgCgHIAAgIIgBgHIgBgIIAAgHIgFgIIgDgHIgFgIIgDgHIgBgIIgBgHIAAgIIgDgHIgEgIIgBgFIgTgIQgYgKgQgUQgNgQgFgVIAAgHIgBgIIgCgHIACgIIABgHIACgIIABgHIAEgIIAEgHIAEgIIAIgHIAHgIIAIgHIAOgIIAKgFIAKgCIAVgCIAAgBQBDgGAyAsQApAlAJA1IAFAHIACAIIACAHIABAIIAAAHIADAHIAEAIIABAHIACAIIAEAIIADAHIADAIIABAHIACAPIACAPIAFAPIAAAIIAAAHIAEAIIAEAHIACAIIAAAHIAAAIIACAHIADAHIAFAIIADAHIAFAIIAAAHIACAIIADAHIAFAIIAAAHIABAIIABAHIACAIIAFAPIADAIIAAAHIAAAIIAFAHIADAHIAEAIIADAIIACAHIADAIIAAAHIABAIIABAHIABAIIAAAHIADAIIACAHIADAPIAEAPIAFAPIABAPQABANACALIALAkQAEAPABAPIADAHIAFAIIAAAIIABAHIABAIIABAHIACAPIACAIQAPgHAQgLQArgeApgiQAOgLALgMQAjgPAhgTQAugcAzgVQAggIAhADQAtADAeAjIAFAHIADAHIAHAQIAIAOIAEAIQAJA4gBA5QgCBdAABeIAABEIACAHIACAIIADAHIAAAIIABAHIABAPIABAPIAAAPIAHgBIAPgGIAKgFIAFgDQArgKAtAEQAhADAaAVIAIAIIAFAHIAFAHIAFAIIAIAPIABAHIABAIIAAAHIAAAIIAAAHIAAAIIgGAOQgFAMgHALQgRAYgcALIgJACIgUAEIgcAEIgKAIIgNAHIgKAFQgoANgmAAQg+AAg3gigAca0/QhJgTgxg6QgMgOgGgSIgXgWQgOgNgJgSQgGgKgDgMIAAgHIAAgIIgDgHIADgIIABgHIABgIIABgHIAEgIIAEgHIAEgIIAHgHIAIgIIAIgHIAOgIIALgFQBOgRA0BBQAYAeAaAeIBXAFIAFgCIAKgDIAPgFQAMgLALgNIAWgWIAHgHIAFgIIADgHIAFgHQAqgrAdg1IA+hyIADgPIAEgPIAGgXIABgHIAFgIIADgHIAFgIIAFgHIAAgIIACgHIAEgIIADgIIAEgHIAEgHIACgIIABgHIAAgIQAGgUAJgTQAPgiAegZIAIgHIAPgHIAKgFQApgOAkAXQAUANAPASIAFAHIADAHIAFAIIAHAIIA8AHIAQgHIARgIQAgghAdgjQAhgqAagvIAFgXQADgMAEgMQAHgPAKgNIADgIIAAgHIAAgIIADgHIACgIIACgHIAAgIIACgHIABgIIAAgHIAAgIIADgHIACgIIADgHIAAgPIABgIIABgIIAAgOIAFgPIADgIIAEgIIAIgOIABgIIABgHQAHgRAMgNQAagdAmgOQCggZBzBxIAIAHQAdgJAWgaQAbggAegfIA/hdQAlg2AtgwIAPgHIAKgFIAKgCIATgCIAAgBIAXAEQAOAFANAGIANAHIAMAQIAFAHIAIAPIAFAHIACAQIABAHIAAAHIAAAPIgKAfQgIAVgOARQgHAKgGALQgiAhgZAoQgfAygrArQgfAugrAlQgtAmgzAaQhGAVg6gmIgZgPIglgmQgjgigeAHIgCAHIgBAIIAAAHIgCAIIgCAHIgDAIIAAAHIgBAHIgBAIIgBAIIAAAHIgEAPIgEAPIgEAXIAAAHIgIAPIgJAQIgHAOIgEAIIAAAHIgCAIIgEAHIgEAIIAAAHIgDAIQgHATgLATQgTAegXAcIgPAQIgEAIIgEAHIgEAIQgtAtguArQgnAkg1ASQhbAShdgSQglBdgyBYQgyBYg7BUQhnCSikAAQg0AAg6gPg");
	this.shape.setTransform(-17.75,4.7566);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFF00").s().p("EADEAwiQghgOgbgYQhXgrhQgyQglgXgNgpIAAgIIAAgHIgCgIIAAgHIAAgIIACgHIABgIIABgHIABgIIAEgIIAEgHIAEgHQBGhDBagoQA6gaAugqQAIgEAEgGQABgCgDgDQgOgOgQgMIgjgaQgHgFgIgDIgXgWQgSgSgPgVQgLgSgKgTIgCgPIgDgWQAAgPACgPQACgLgCgMIAGgPIALgXQAIgQALgPQAGgGADgHIAtgzQAogvAwglIABgIIAAgHIABgIIABgHIACgPIAEgIIAEgHIAEgIIAIgHIAHgIIAIgHIAPgIIAKgFIAKgCIAUgCIAAgBQAkgDAfATQAYAPATAWIAEAHIAEAHIAEAIIADAHIAFAIIAAAHIACAIIABAHIACAIIgCAIIgBAHIgCAIIAAAHQgTAngiAcQg7Avg4AzIgDAHIgEAIIgGAHIgNAQIgEAHQAyAsA2ApQA0AoAgA3IAAAIIACAHIABAIIACAHIgBAIIgBAHIgBAIIAAAHQgXBDg3AsQhLA8hUAvQAKANAnAXQAvAcATAzIACAHIAAAIIAAAHIAAAIIAAAPQgCAMgGALQgIARgOAMQgPAMgRAIQgPAFgPAAQgRAAgSgHgEgn8AMvQgmgBgXghQhjiThEimIgHgIIgFgHIgFgIIgIgPQgMADgKALQgNAPgMAQIgPAXIgIAHIgMAIQgoAygdA5QgiBChBAlQiIAMg1iEQgYg+gbg9IgCgHIgBgIIgHgPIgHgPIgIgWIgDgIIAAgHIAAgIIgCgHIACgIIAAgHIAAgIQADgMAHgLQAOgYAYgNIAPgHQAagJAaAHQAhAJAWAZQAJAOAIAQIAdA8IAMAXIABAHIACAHIAFAGIACgDIAIgPIAKgOIAPgQQAZgqAlgkQAtgsAwgrIAPgHIAKgFQCxgqBHCaIAdA/IACAHIABAIQAaAiAPApQAWA6AgA2IAFAFQAlgPAbgeQAggkAigiQAEgMAJgJQAWgWAUgYIAPgPQAeg0AXg4QAWg1AmgpQAOgQAUgHIAKgCIAUgCIAAgBQASADAQAHQAOAFAMAHIAHAIIAGAHIAJAPIAIAPIABAHIABAIIABAHIACAIIgCAIIAAAHIAAAIQgNAlgQAkQgaA8gmA2IgHAIIgDAHIgFAIIgFAHIgPAPIgEAIIgEAHIgEAIIgIAHIgHAIIgIAHIgHAIIgIAOQgIANgLALQgMAMgOAKIgFAHIgEAIIgEAHIgEAIQhxCEikAAIgNAAgEAo7AI6IgBgeQgCglAAgmIAAhLIgBgHQgFgKgBgNQgBgPgEgPQgFgPgDgPQhKA+hPA3QhcBCg4hgQgEgHgCgHIAAgIIgBgHIgCgIIACgHIABgIIACgHIAAgIIAFgIIADgHIAFgHQA8gyA6g0QBKhDBYguIAKgCIAUgCIAAgBQA6gKAtAjQAqAiAPA1IAAAIIAAAHIAEAIIADAHIACAIIABAHIACAPIAEAPIAEAPIAAAIIABAHIABAIIAAAHQCAhZCQhJQBigyBOBDIAFAIQAFALAEALIAMAeIAMAXIAAAHIACAIIADAHIAIAPQAGAKAEAMIAJAfIAAAHIAAAIIAFAHIADAIIABAHIADAPIADAWQACAPgCAQIAAAHIgDAIIgKAWQgJATgSALIgWANQgQAEgRAAQgzgCgegqQgHgLgEgMIgCgHIgBgIIgCgPIgEgPIgEgPIAAgHIAAgIIgEgIIgEgHIgEgIIgDgHQhUAahPA9QhBAzg3A+IgDAHIgEAIQgeAignATQggAQgZAAQg1AAgahFgEAEQgkqIgGgFQglgLgkgjQgYgXgXgbIgMgXQgGgPgIgOQgIgOgEgRIgBgeQgBgSAAgTIACgmQAIgfAZgVQAlggAtgVQgTgNgPgSQgQgUgJgYIgGgPIAAgPIgCgPQgCgLADgMQABgHAAgHQAbhDBEgaQA+gYA9gcIAIgHIAKgIIAOgIIAPgPIAIgHIAHgIIAPgHIAKgFIAKgCIAUgCIAAgBQAMABAKADQAPAFANAGIANAHIAMAPIAFAIIAIAPIAFAHIACAPIAAAIIAAAHIAAAPIgFAPIgFAPIgKAXIgFAHQgcAZgeAWQgcATgdARQAkAhAsAYQAeAQANAgIABAHIABAIIABAHIABAIIABAHIgBAIIgBAHIgBAIIAAAHIgFAPIgDAIIgEAIIgIAOQheA3hxARQgTADgTAFQAcAcAjAVQAVALALAUIAKAQIAIAOIAAAIIACAIIABAHIACAHIgCAIIgBAHIgCAIIAAAHIgFAIIgDAHIgFAIIgFAHIgFAIQggAdghAAQgeAAgfgXg");
	this.shape_1.setTransform(-33.3375,-30.2281);
	this.shape_1._off = true;

	this.timeline.addTween(cjs.Tween.get(this.shape).to({_off:true},2).wait(2).to({_off:false},0).to({_off:true},2).wait(2).to({_off:false},0).to({_off:true},2).wait(2).to({_off:false},0).to({_off:true},2).wait(2).to({_off:false},0).to({_off:true},2).wait(2).to({_off:false},0).to({_off:true},2).wait(2));
	this.timeline.addTween(cjs.Tween.get(this.shape_1).wait(2).to({_off:false},0).to({_off:true},2).wait(2).to({_off:false,y:-68.2281},0).to({_off:true},2).wait(2).to({_off:false,y:-30.2281},0).to({_off:true},2).wait(2).to({_off:false,y:-62.2281},0).to({_off:true},2).wait(2).to({_off:false,y:-30.2281},0).to({_off:true},2).wait(2).to({_off:false,y:-66.2281},0).wait(2));

	// Stem
	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#660000").s().p("ADIIUIgIgGIgFgIIgCgHIgBgFQgDgNABgPQACgaAAgaIAAg0IgCgIIgGgOIgIgRIgEgOIgDgHIgEgIIgDgHIAAgIIAAgHIgCgIIgDgHIgCgIIgDgHIAAgIIAAgHIgCgIIgFgIIgCgHIgBgHIAAgIIgDgHIgEgIIgBgHIgCgIIgDgHIgEgIIgBgHIgBgIIgBgHIAAgIIAAgHIgBgHIgCgGIgBgDIgDgHIgBgHIgCgIIgDgHIgEgIIgBgHIgEgPIgIgXIgHgPIgBgGIgBgIIgBgHIAAgIIgEgIIgGgOIgCgIIgDgHQgMgNgIgRQgIgUgJgSIgNgWIgHgIIgHgHIgGgIIgEgHIgMgJIgPgOIgIgHIgRgIIgUgKIgIgHIgHgIIgIgHQgLgHgMgEIgdgLIgIABIgWABIgogLIgPgEIgIgIIgHgHIgIgIIgCgHIgCgIIgBgHIgEgIIgDgHIgDgIIgHgHIgIgIIgCgHQgBgEgDgDQgCgFgEgDIgBgIIgBgPIgBgPIgCgHQgJgKABgNIABgeIACgWIAHgIIAIgHIAHgIIAPgEIAAgBQAXAHAQASIAkAoIAPAIQApgEAbAcIAHAIQAZALAUAQQAOALANANIAGAHIBeAFQASAFALAPQAJAOAOAIIAJAOIAPAYQAFAHAEAIIAFAGIAJAJIAGAHIAEAIIABAHIACAIIADAHIAFAIIAAAHIACAIIAAAHIAAAIIAJAVQAGALAFAMQADAIAFAIIAAAHIACAIIAAAHIAAAIIABAHIAEAIIADAHIACAIIAAAHIAFAIIADAHIACAIIAAAHIAHAIIAGAHIAEAIIABAGIACAIIAGAHIAHAIQACAHAEAHQAHALAFAMIAHAPIACAPIAAAPIAAAPIAAAIIADAHIAFAIIAAAHIACAIIADAHQAEAIAEAGIAMAQQAMAjgDAoQgCAaAAAbIAAA0IAAAWIgCAQIgFAHIgFAIIgDAHIgCAIIgIAHIgHAIIgDAHIgCAIIgIAHIgHAIIgIAHIgDAHIgEAIQgJAIgKAGIgHAFIgCABIgFADIgBAAIgJAFQgHgDgHgEg");
	this.shape_2.setTransform(-18.4048,-206.825);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#660000").s().p("ADIIUIgIgGIgFgIIgCgHIAAgFQgEgNABgPQACgaAAgaIAAg0IgCgIIgGgOIgIgRIgEgOIgDgHIgEgIIgDgHIAAgIIAAgHIgCgIIgDgHIgCgIIgDgHIAAgIIAAgHIgCgIIgFgIIgCgHIgBgHIAAgIIgDgHIgEgIIgBgHIgCgIIgDgHIgEgIIgBgHIgBgIIgBgHIAAgIIAAgHIgBgHIgCgGIgBgDIgDgHIgBgHIgCgIIgDgHIgEgIIgBgHIgEgPIgIgXIgHgPIgBgGIgBgIIgBgHIAAgIIgEgIIgGgOIgCgIIgDgHQgMgNgIgRQgIgUgJgSIgNgWIgHgIIgHgHIgGgIIgEgHIgMgJIgPgOIgIgHIgRgIIgUgKIgIgHIgHgIIgIgHQgLgHgMgEIgdgLIgIABIgWABIgogLIgPgEIgIgIIgHgHIgIgIIgCgHIgCgIIgBgHIgEgIIgDgHIgDgIIgHgHIgIgIIgCgHQgBgEgDgDQgCgFgEgDIgBgIIgBgPIgBgPIgCgHQgJgKABgNIABgeIACgWIAHgIIAIgHIAHgIIAPgEIAAgBQAXAHAQASIAkAoIAPAIQApgEAbAcIAHAIQAZALAUAQQAOALANAOIAGAGIBeAFQASAFALAPQAJAOAOAIIAJAOIAPAYQAFAHAEAIIAFAGIAJAJIAGAHIAEAIIABAHIACAIIADAHIAFAIIAAAHIACAIIAAAHIAAAIIAJAVQAGALAFAMQADAIAFAIIAAAHIACAIIAAAHIAAAIIABAHIAEAIIADAHIACAIIAAAHIAFAIIADAHIACAIIAAAHIAHAIIAGAHIAEAIIABAGIACAIIAGAHIAHAIQACAHAEAHQAHALAFAMIAHAPIACAPIAAAPIAAAPIAAAIIADAHIAFAIIAAAHIACAIIADAHQAEAIAEAGIAMAQQAMAjgDAoQgCAaAAAbIAAA0IAAAWIgCAQIgFAHIgFAIIgDAHIgCAIIgIAHIgHAIIgDAHIgCAIIgIAHIgHAIIgIAHIgDAHIgEAIQgJAIgKAGIgHAFIgCABIgFADIgBAAIgJAFQgHgDgHgEg");
	this.shape_3.setTransform(-20.4048,-244.825);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_2}]}).to({state:[{t:this.shape_3}]},4).to({state:[{t:this.shape_2}]},4).to({state:[{t:this.shape_3}]},4).to({state:[{t:this.shape_2}]},4).to({state:[{t:this.shape_3}]},4).wait(4));

	// Leaf
	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#000000").s().p("AimCNIgKgGIgDgHIgDgIIgEgIIgCgIIgCgOIgBgFQgSAMgWAIIgPAHIhkAAQgGgDgBgGQgDgFAAgIIADgHIAHgFIAHgDIBQgFQAcgQAdgOIAAgLQABgaAEgZQADgDADgCQAGgEAGgBIAFAAIAJAIQADADAAAFQAFAKgBALIgBAPIAhgOIAegKIA6gEQgCgRAAgRIACgtIABgHIAGgFIAEgCIAIgBIAFAAIAJAIQACADABAEQADALAAAMIgBAWIAAAIIAFAOQAegKAegMIBIgFIAAgKQABgiAEghIAGgFIAEgCIAIgBIAFAAIAJAJQACACABAFQAEASAAATIgBAOQASgLAWgDQAggYAggXQAJgGAHgHIAPgIIANgHIAMgDIAFAAIAJAIQACAEABAEIAAAHQgBADgCADQgDAFgDAEIgVAOIgMAJIgHAHIgFAIQggAQgdAVIgKAIIgZAHIgJAHIgLAKIADAIIAAAGIAAAIIANAOQAJAKgCANQgBAEgDADQgHAHgJAGIgPgEIgKgQIgNgPIgBgIIgCgOQAAgEgBgEIgEgGIhCAEQgcALgbAJIABAEIAKAXIAEAIIACAIIAAAHIAIAOQAHALADANQAAADgCACQgHAIgJAHIgRgGIgKgHIgEgHIgGgQIgDgHQAAgIgDgGQgFgMgFgMIgEgHIgBgHIgDACIhHAFQgdAMggAIIABAFQACADAAAFIACAOIABAIQAKANAMALQAHAGAHAHIgBAHQgBAFgBADIgFAIIgSACIgdgQg");
	this.shape_4.setTransform(44,-241.45);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#003300").s().p("AlrDeQg8gLg8gVIgHgIIgFgFIgFgCQgIgDgGgEIgJgGQgDgHgCgIQgBgHADgHQACgFAEgDQAFgEAFgCQAOgGANgDIAGgPIAEgIIADgHIACgIIAAgHQAXgSAKgaIARgtIAegeIAXgXIAIgEIAMgGIAHgHIAFgFIASgIIAUgKIAHgHIAFgFQAOgFAMgHIAggQIAHgHIAFgFQBGgQBBgbQAfgEAdgIIF2gFQBJgHA+gIQAJACAHAFQAJAFAIAIIADAPQACALAAALIAAAPIgDAIIgCAHIgDAIIgHAHIgIAIIgCAHIgDAIQgNAKgLAKQgJAKgMAHIgDAHIgEAIIgQAPIgRAPQgNAYgPAVQgPAVgOAXIhDBFQgUAVgaAPIgDAHIgEAIQgSAKgPAMQgMAKgKANQgZAPgeAAQgGAAgHADIhNAFIgNAFIkeAAIgJAAQg0AAgqgXgAjJBQIACAOIABAIIAFAIIADAHIACAIIALAGIAdAQIASgCIAEgIQACgEABgEIAAgHQgGgHgHgHQgMgLgKgMIgBgIIgCgPQAAgEgCgDIgBgFQAggIAdgMIBGgFIAEgCIABAHIADAHQAGALAFAMQADAHABAIIADAHIAGAPIACAIIAKAHIASAFQAJgGAGgIQACgCAAgEQgCgMgHgLIgIgOIgBgIIgCgHIgDgIIgKgXIgCgEQAcgJAbgKIBDgFIADAHQACAEAAADIACAOIABAIIAMAPIALAPIAPAFQAJgGAHgIQADgCABgEQABgNgJgKIgMgOIAAgHIAAgHIgDgIIALgKIAJgHIAZgIIAKgHQAdgVAfgRIAGgHIAHgIIAMgIIAUgOQAEgEADgFQACgDABgEIAAgHQgBgEgCgDIgJgIIgFAAIgNADIgMAHIgPAIQgIAHgIAGQghAWgfAZQgWADgSALIABgOQAAgUgEgSQgBgEgCgDIgJgIIgFAAIgIABIgEACIgGAFQgEAhgCAiIAAAKIhHAFQgeAMgdAKIgFgOIAAgIIABgWQAAgMgEgLQgBgEgCgDIgJgIIgFAAIgIABIgEACIgGAFIgBAHIgCAtQgBARADARIg7AEIgdALIghANIABgOQAAgMgEgLQgBgEgCgDIgJgIIgFAAQgGABgGADQgDACgDAEQgEAagBAZIAAALQgdAOgcAQIhQAFIgHADIgHAFIgEAHQAAAHADAGQACAFAFAEIBkAAIAQgHQAVgIATgMIABAFg");
	this.shape_5.setTransform(45.1125,-240.4425);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#000000").s().p("AimCNIgLgGIgCgHIgDgIIgFgIIgBgIIgCgOIAAgFQgUAMgVAIIgPAHIhkAAQgGgEgBgFQgDgFgBgIIAEgHIAHgFIAHgDIBQgFQAcgQAdgOIAAgKQABgbAEgZQADgDAEgDQAFgDAGAAIAFAAIAJAIQACACABAFQAEAKAAALIgBAPIAhgOIAdgKIA8gEQgDgQAAgRIACgtIABgIIAGgFIAEgCIAIgBIAFAAIAJAIQACADACAFQACAKAAAMIgBAXIAAAHIAFAOQAegKAegLIBHgGIAAgKQACgiAFghIAFgFIAEgCIAIAAIAFAAIAJAIQACACACAEQADATAAATIgBAOQARgLAXgDQAfgYAhgXQAIgGAIgHIAPgIIANgHIAMgDIAFAAIAJAJQACACACAFIgBAGQgBAFgCACQgCAFgEAEIgVAPIgMAIIgHAHIgFAHQggARgdAVIgJAHIgaAIIgJAHIgKAKIACAIIAAAHIAAAHIANAOQAIALgBANQgBADgDACQgHAIgJAGIgPgFIgLgOIgMgQIgBgIIgCgOQAAgEgBgDIgEgHIhCAEQgbALgcAJIABAEIALAYIACAHIADAHIAAAIIAIAPQAHAKADAMQgBAEgCACQgGAIgJAHIgRgGIgKgHIgEgIIgGgPIgDgHQAAgHgDgIQgEgMgGgLIgEgHIgBgHIgDACIhGAFQgeAMggAIIABAFQACADAAAFIACAOIACAIQAJAMAMAMQAHAGAHAHIgBAHQgBAEgCAEIgEAIIgRACIgegQg");
	this.shape_6.setTransform(42,-279.45);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#003300").s().p("AlrDeQg8gLg8gVIgHgIIgFgFIgFgCQgIgDgGgEIgJgGQgDgHgCgIQgBgHADgHQACgFAEgDQAFgEAFgCQAOgGANgDIAGgPIAEgIIADgHIACgIIAAgHQAXgSAKgaIARgtIAegeIAXgXIAIgEIAMgGIAHgHIAFgFIASgIIAUgKIAHgHIAFgFQAOgFAMgHIAggQIAHgHIAFgFQBGgQBBgbQAfgEAdgIIF2gFQBJgHA+gIQAJACAHAFQAJAFAIAIIADAPQACALAAALIAAAPIgDAIIgCAHIgDAIIgHAHIgIAIIgCAHIgDAIQgNAKgLAKQgJAKgMAHIgDAHIgEAIIgQAPIgRAPQgNAYgPAVQgPAVgOAXIhDBFQgUAVgaAPIgDAHIgEAIQgSAKgPAMQgMAKgKANQgZAPgeAAQgGAAgHADIhNAFIgNAFIkeAAIgJAAQg0AAgqgXgAjJBQIACAOIABAIIAFAIIADAHIACAIIALAGIAdAQIASgCIAEgIQACgEABgEIAAgHQgGgHgHgHQgMgLgKgMIgBgIIgCgPQAAgEgCgDIgBgFQAggIAdgMIBGgFIAEgCIABAHIADAHQAGALAFAMQADAHABAIIADAHIAGAPIACAIIAKAHIASAFQAJgGAGgIQACgCAAgEQgCgMgHgLIgIgOIgBgIIgCgHIgDgIIgKgXIgCgEQAcgJAbgKIBDgFIADAHQACAEAAADIACAOIABAIIAMAPIALAPIAPAFQAJgGAHgIQADgCABgEQABgNgJgKIgMgOIAAgHIAAgHIgDgIIALgKIAJgHIAZgIIAKgHQAdgVAfgRIAGgHIAHgIIAMgIIAUgOQAEgEADgFQACgDABgEIAAgHQgBgEgCgDIgJgIIgFAAIgNADIgMAHIgPAIQgIAHgIAGQghAWgfAZQgXADgRALIABgOQAAgUgEgSQgBgEgCgDIgJgIIgFAAIgIABIgEACIgGAFQgEAhgCAiIAAAKIhHAFQgeAMgdAKIgFgOIAAgIIABgWQAAgMgEgLQgBgEgCgDIgJgIIgFAAIgIABIgEACIgGAFIgBAHIgCAtQgBARADARIg7AEIgdALIghANIABgOQAAgMgEgLQgBgEgCgDIgJgIIgFAAQgGABgGADQgDACgDAEQgEAagBAZIAAALQgdAOgcAQIhQAFIgHADIgHAFIgEAHQAAAHADAGQACAFAFAEIBkAAIAQgHQAVgJATgLIABAFg");
	this.shape_7.setTransform(43.1125,-278.4425);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_5},{t:this.shape_4}]}).to({state:[{t:this.shape_7},{t:this.shape_6}]},4).to({state:[{t:this.shape_5},{t:this.shape_4}]},4).to({state:[{t:this.shape_7},{t:this.shape_6}]},4).to({state:[{t:this.shape_5},{t:this.shape_4}]},4).to({state:[{t:this.shape_7},{t:this.shape_6}]},4).wait(4));

	// AppleCore
	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f().s("rgba(0,0,0,0)").ss(0.1,1,1).p("A7hGlQgXiTAAidQAArjIKoLQILoKLjAAQLjAAILIKQILILAALjQAAAsgBArA4OOBQBEiSB8h8QETkTGFAAQGFAAETETQAfAgAdAiQAcgiAgggQEUkTGEAAQGGAAETETQBWBWA7BhAivWUQgJhCAAhGQAAlYDWj/AhtaEQgBgCgBgD");
	this.shape_8.setTransform(-0.35,-8.025);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#000000").s().p("AiBCbQiOgHiFgmIgIgHIgFgGIgCgCIgPgFIgIgHIgHgIIgIgHIgCgIQgBgEgDgDQgCgFgEgDQgEgpAAgpQgBgxAFgwQACgEAEgCIAVgNIAAgBIAMAGIALAHIACAHIADAHIACAIIAAA8IAABCIAAAIIADAHIAFAIQAAABAAAAQAAABAAAAQAAABAAAAQABAAAAAAIAVAPIAIAHIAMAFIA6AFIBIAPIBiAFIAMAFICxAAQAogIAogMIAIgIIAHgEQAlgIAhgPIAPgFIAHgHIAIgIIAFgFIAFgCIAKgDIAPgFIAPgOIAWgXIAIgEIAMgGIAIgHIAFgFIAFgCIAKgEIAPgEIAHgHIAIgIIAFgFIAFgDIAMgGIAKgGIAPgFQAHADAFAEQAHAFAFAIQADAEABADIgBAIIgCAIIgCAHIgIAIIgHAHIgFAFIgFACIgNAGQgHAHgJAGQgLAJgNAHIgHAHIgFAFIgFACIgNAFIgHAIIgFAFIgFACIgNAGQgLAMgPAIQgMAHgOAFIgIAHIgHAIIgFAFIgPAEQgWAFgSAOIgKABIgZAGIgIAHIgHAFQgtANgtAKIjCAAg");
	this.shape_9.setTransform(9.2975,-147.7);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FF0000").s().p("AxCaAIgFgCIgjgJQgOgDgJgLQgQgGgOgKQgYgQgcgLQgxgyg1gtQgbgWgXgaIgFgFIgRgNQhUhrhGh2IgdgyQgTgSgNgXIgxhQIgCgIIAAgHIgDgHIgFgIIgFgIIgFgHIgBgIIgDgOQgCgLABgMIAAgPQgHgjgEgkIgFgHIgJgOIgRgXQgJgZAAgcIACgpQgSiLgBiNQgBg3ADgxQgYiTAAidQAArjILoLQILoKLjAAQLjAAIKIKQILILAALjQAAAsgBArIAAABQANBGgGAwQgCARgIAjQgHAhgCASQgDAYABAoIAABBQgBAYgGAgIgKA4IgHAsQgeBNgnBVQgrBdhcC0QglBJgVAlQgiA8ggAtQiJC/jzB7QhvA4hVAMIgCABQgPAHgPAFQgUACgTgDQgvAYg+gEQgTgBgVADQkfAujKixIg3gIQgfgEgfgHIgPgDQgMAHgOAEQgcAIgdAGIgRAMIgJAHIgCgFIACAFIhxBQQgrAcgoASIgBAAQg8AIhyAFIgRABQhoAUhjAAQjKAAi5hUgAi8S8QAABGAJBCQgJhCAAhGQAAlYDWj/QAdgiAgggQETkTGFAAQGFAAETETQBWBWA7BhQg7hhhWhWQkTkTmFAAQmFAAkTETQggAggdAiQjWD/AAFYIAAAAgA1SIjQh7B8hECSQBEiSB7h8QETkTGFAAQGFAAEUETQAgAgAbAiQgbgiggggQkUkTmFAAQmFAAkTETgAle5dIgVAMQgDACgDAEQgEAwAAAyQAAApAEApQAEAEADAEQACADABAEIADAIIAHAHIAIAIIAHAHIAPAGIADACIAFAFIAHAHQCGAmCNAHIDCAAQAugJAsgNIAHgGIAIgHIAZgFIAKgCQASgOAWgFIAPgEIAFgFIAIgHIAHgIQAOgFANgHQAPgIALgMIAMgGIAFgCIAFgFIAIgHIAMgGIAFgCIAFgFIAIgHQAMgIAMgJQAIgGAIgHIAMgGIAFgCIAFgFIAIgHIAHgIIADgHIACgIIAAgHQgBgEgCgDQgFgIgIgGQgFgEgGgDIgPAFIgLAHIgMAGIgFACIgFAFIgHAIIgIAHIgPAFIgKADIgFACIgFAFIgHAIIgMAFIgIAFIgXAWIgPAPIgPAFIgKADIgFACIgFAFIgHAIIgIAHIgOAGQgiAPglAHIgHAFIgIAHQgnANgpAHIiwAAIgNgFIhhgFIhJgPIg5gFIgNgFIgIgHIgUgOQgBgBAAAAQAAAAAAgBQgBAAAAgBQAAAAAAgBIgEgIIgDgHIAAgHIAAhEIAAg8IgDgHIgCgIIgDgHIgKgHIgMgGIgBACgAhwY0IAAAAg");
	this.shape_10.setTransform(0.0318,-0.0054);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f().s("rgba(0,0,0,0)").ss(0.1,1,1).p("A7hGlQgXiTAAidQAArjIKoLQILoKLjAAQLjAAILIKQILILAALjQAAAsgBArAivWUQgJhCAAhGQAAlYDWj/QAcgiAgggQEUkTGEAAQGGAAETETQBWBWA7BhA4OOBQBEiSB8h8QETkTGFAAQGFAAETETQAfAgAdAiAhtaEQgBgCgBgD");
	this.shape_11.setTransform(-2.35,-46.025);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#000000").s().p("AiBCbQiOgIiFglIgIgHIgFgGIgCgBIgPgGIgIgIIgHgHIgIgHIgCgIQgBgEgDgDQgCgFgEgDQgEgpAAgpQgBgxAFgwQACgEAEgCIAVgNIAAgBIAMAGIALAGIACAIIADAHIACAIIAAA8IAABCIAAAIIADAHIAFAIQAAABAAAAQAAABAAAAQAAABAAAAQABAAAAABIAVAOIAIAHIAMAFIA6AFIBIAPIBiAFIAMAFICxAAQAogIAogMIAIgIIAHgEQAlgIAhgPIAPgFIAHgHIAIgIIAFgFIAFgCIAKgDIAPgFIAPgOIAWgXIAIgEIAMgFIAIgIIAFgFIAFgCIAKgDIAPgFIAHgHIAIgIIAFgFIAFgCIAMgHIAKgGIAPgFQAHADAFAEQAHAGAFAHQADADABAEIgBAIIgCAIIgCAHIgIAHIgHAIIgFAFIgFACIgNAGQgHAHgJAGQgLAJgNAIIgHAGIgFAFIgFACIgNAFIgHAIIgFAFIgFACIgNAFQgLANgPAIQgMAHgOAFIgIAIIgHAHIgFAFIgPAEQgWAFgSAOIgKACIgZAFIgIAHIgHAGQgtAMgtAKIjCAAg");
	this.shape_12.setTransform(7.2975,-185.7);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FF0000").s().p("AxCaAIgFgCIgjgJQgOgDgJgLQgQgGgOgKQgYgQgcgLQgxgyg1gtQgbgWgXgaIgFgFIgRgNQhUhrhGh2IgdgyQgTgSgNgXIgxhQIgCgIIAAgHIgDgHIgFgIIgFgIIgFgHIgBgIIgDgOQgCgLABgMIAAgPQgHgjgEgkIgFgHIgJgOIgRgXQgJgZAAgcIACgpQgSiLgBiNQgBg3ADgxQgYiTAAidQAArjILoLQILoKLjAAQLjAAIKIKQILILAALjQAAAsgBArIAAABQANBGgGAwQgCARgIAjQgHAhgCASQgDAYABAoIAABBQgBAYgGAgIgKA4IgHAsQgeBNgnBVQgrBdhcC0QglBJgVAlQgiA8ggAtQiJC/jzB7QhvA4hVAMIgCABQgPAHgPAFQgUACgTgDQgvAYg+gEQgTgBgVADQkfAujKixIg3gIQgfgEgfgHIgPgDQgMAHgOAEQgcAIgdAGIgRAMIgJAHIgCgFIACAFIhxBQQgrAcgoASIgBAAQg8AIhyAFIgRABQhoAUhjAAQjKAAi5hUgAi8S8QAABGAJBCQgJhCAAhGQAAlYDWj/QAdgiAgggQETkTGFAAQGFAAETETQBWBWA7BhQg7hhhWhWQkTkTmFAAQmFAAkTETQggAggdAiQgbgiggggQkUkTmFAAQmFAAkTETQh7B8hECSQBEiSB7h8QETkTGFAAQGFAAEUETQAgAgAbAiQjWD/AAFYIAAAAgAle5dIgVAMQgDACgDAEQgEAwAAAyQAAApAEApQAEAEADAEQACADABAEIADAIIAHAHIAIAIIAHAHIAPAGIADACIAFAFIAHAHQCGAmCNAHIDCAAQAugJAsgNIAHgGIAIgHIAZgFIAKgCQASgOAWgFIAPgEIAFgFIAIgHIAHgIQAOgFANgHQAPgIALgMIAMgGIAFgCIAFgFIAIgHIAMgGIAFgCIAFgFIAIgHQAMgIAMgJQAIgGAIgHIAMgGIAFgCIAFgFIAIgHIAHgIIADgHIACgIIAAgHQgBgEgCgDQgFgIgIgGQgFgEgGgDIgPAFIgLAHIgMAGIgFACIgFAFIgHAIIgIAHIgPAFIgKADIgFACIgFAFIgHAIIgMAFIgIAFIgXAWIgPAPIgPAFIgKADIgFACIgFAFIgHAIIgIAHIgOAGQgiAPglAHIgHAFIgIAHQgnANgpAHIiwAAIgNgFIhhgFIhJgPIg5gFIgNgFIgIgHIgUgOQgBgBAAAAQAAAAAAgBQgBAAAAgBQAAAAAAgBIgEgIIgDgHIAAgHIAAhEIAAg8IgDgHIgCgIIgDgHIgKgHIgMgGIgBACgAhwY0IAAAAg");
	this.shape_13.setTransform(-1.9682,-38.0054);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_10},{t:this.shape_9},{t:this.shape_8}]}).to({state:[{t:this.shape_13},{t:this.shape_12},{t:this.shape_11}]},4).to({state:[{t:this.shape_10},{t:this.shape_9},{t:this.shape_8}]},4).to({state:[{t:this.shape_13},{t:this.shape_12},{t:this.shape_11}]},4).to({state:[{t:this.shape_10},{t:this.shape_9},{t:this.shape_8}]},4).to({state:[{t:this.shape_13},{t:this.shape_12},{t:this.shape_11}]},4).wait(4));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-381.8,-379.5,728.2,660.6);


(lib.circlebutton = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#000000").ss(4,1,1).p("ALLmwQAABDgsAuQgsAvg+AAQg+AAgsgvQgsguAAhDQAAhCAsgvQAtgvA9AAQA+AAAsAvQAsAvAABCgAmenEQAABDgsAuQgsAvg+AAQg+AAgsgvQgsguAAhDQAAhCAsgvQAsgvA+AAQA+AAAsAvQAsAvAABCgAgYFcQAABshMBLQhMBNhsAAQhsAAhMhNQhMhMAAhrQAAhsBMhNQBNhMBrAAQBsAABMBMQBMBNAABsgAINFhQAABshMBLQhMBNhsAAQhrAAhNhNQhMhMAAhrQAAhsBMhNQBNhMBrAAQBsAABMBMQBMBNAABsg");
	this.shape.setTransform(26.3,-0.55);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f().s("#000000").ss(5,1,1).p("AqDxbQEfipFkAAQHBAAFTEMQA+AxA7A7QDSDSBdEEAx0pWQBYinCQiPQBohoB0hMATRl2QA0CxAADFQAAIUl4F5Ql5F4oUAAQoUAAl4l4Ql4l5AAoUQAAktB5j8");
	this.shape_1.setTransform(27.8,3.15);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#000000").s().p("AmiRxQhNgQgiglQgJgKgOgWIgthEQgKgPgCgLQgDgSALgHQAIgGAMAEQAJADAJAIQARAPAYApQAXAnASAPQATARAfAJQATAGAkAFQCoAXCPgIQA5gEAggKQAegKA8gjQA6giAigJQAXgGAOAFQAJAEAGAJQAFAJgDAJQgEANgcAIQghAKg4AgQg6AigdAKQgmAOgxAFQghADg6AAQi7gBhpgXgABsKfQgygJgigrQgigqgBgzQAAgzAhgqQAigrAygLQAygKAxAZQAwAZAVAvQAUAvgPA0QgPA1gpAdQgZASgeAGQgQADgPAAQgPAAgOgDgAm5KfQgygJgigrQgjgqgBgzQAAgzAigqQAigrAygLQAygKAxAZQAwAZAVAvQAUAvgPA0QgPA1gpAdQgZASgeAGQgQADgPAAQgPAAgOgDgAFCioQgsguAAhDQAAhDAsgvQAsguA+AAQA+AAAsAuQAsAvAABDQAABDgsAuQgsAvg+AAQg+AAgsgvgAsni8QgsgvAAhCQAAhDAsgvQAsguA+AAQA+AAAsAuQAsAvAABDQAABCgsAvQgsAvg+AAQg+AAgsgvgARAjEQgFgMABgPQACgNAEgPQAJgmAWguIA0hsQAXg0AlhxQAmhfA3gtQAtgkBIgSQAjgJBggNQCPgSCLghQgMgmgLgTQgRgegZgLQgSgJgmgBQifgEhiABQiMAChzANQkbAfjRBpQgbAOgQgBQgMgBgJgIQgJgJACgLQADgOAXgMQDThlDkglQCHgWCsgEQBqgCDLAGQAgABATADQAcAFASAOQAWAQAVArQAYAxAOAPIALAMQAGAIABAGQACAPgPALQgMAIgTAEQiuAoiwAYQhEAKggAIQg2APgiAcQggAcgYAwQgMAagXBBQgbBMgnBbQgaA7gwBpQgGANgHAFIgFABIgDAAQgJAAgGgLgA0JluQgTgBgNghIgYg/QgQgpgLgTQgLgWgbgqQgIgOgPghQgPgfgJgQQgXgogngnQgigkgogbQg7gphSgaQhAgUhagPQgUgDgMgHQgRgKABgPQAAgLAPgQQA+hCAnggQA9gxA8gPQAcgHAjgCQAXgCAoABQDmADDZALQA1ACAcAJQAPAFAUAKIAhASQAQAJAsATQAmASAVAMQBEAnAUA2QAEAMABAKQABALgEAJQgEAKgLAFQgLAFgJgGIgHgGQgCgDgCgFIgGgRQgMgogygdQgbgRg7gYIgtgZQgbgPgUgFQgXgHgqgCQjhgMjLgDQg4gBgeADQgwAFgkAPQgiAPgjAeQgYAUgkAnQBeAYAwAQQBNAaA4AiQBRA0A9BUQAeAqAkBFQARAgA0BoIAbA4QAIAQADAMQACAJgBAGQgBAMgIAJQgHAIgIABIgEAAg");
	this.shape_2.setTransform(40.0114,-15.5562);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FF66CC").s().p("AwHOQQl5l4AAoUQABktB5j8QAIgCAHgHQAIgJABgMQAAgHgCgIQBZinCQiPQBohoB0hMQh0BMhoBoQiQCPhZCnQgDgMgHgRIgbg4Qg0hogRggQglhFgdgpQg+hVhRgzQg3gjhOgaQgvgQhegXQAjgnAYgVQAkgeAigPQAkgPAvgEQAegDA5AAQDKADDiANQApACAYAGQATAGAcAOIAtAZQA7AZAbAQQAyAeAMAnIAGASQACAEACADIAGAHQAKAFAKgFQALgEAFgKQAEgJgBgLQEeipFmAAQHAAAFSEMIACgDQAJAIAMABQAQABAbgOQDRhpEagfQB0gMCMgCQBigBCeAEQAnABASAIQAZALAQAeQAMAUAMAmQiLAhiQASQhfAMgjAJQhJASgsAlQg3AsgmBgQglBwgXA1Ig1BsQgWAugIAmQhdkEjTjSQg6g7g/gxQA/AxA6A7QDTDSBdEEQgEAOgCAOQgCAOAGAMQAGAOAMgCIAFgCQA0CxAADFQAAIUl5F4Ql4F5oTAAQoVAAl4l5gApaLuQgMAHAEASQACAKAKAPIAsBFQAOAWAKAKQAiAkBNAQQBpAXC7ABQA6AAAhgDQAwgEAmgOQAdgLA7ghQA4ggAhgKQAcgJADgNQAEgJgGgJQgFgIgJgEQgOgGgYAGQghAJg6AiQg9AkgeAJQgfAKg5AEQiPAJiogXQgkgGgUgGQgegJgTgQQgSgPgXgoQgYgpgRgPQgJgIgJgDIgIgBQgHAAgFAEgAiEE/QAABsBLBMQBMBMBsAAQBsAABLhMQBMhMABhsQgBhrhMhNQhMhMhrAAQhrAAhNBMQhLBNAABrIAAAAgAqqE6QgBBsBMBMQBNBMBsAAQBsAABLhMQBMhMAAhsQAAhrhMhNQhMhMhrAAQhrAAhOBMQhMBNABBrIAAAAgAFApCQgsAvAABCQAABDAsAuQAsAvA+AAQA/AAAsgvQAsguAAhDQAAhCgsgvQgsgvg/AAQg9AAgtAvgAsopWQgtAvABBCQgBBDAtAuQAsAvA9AAQA/AAArgvQAsguAAhDQAAhCgsgvQgrgvg/AAQg9AAgsAvgAg5H3QhLhMAAhsQAAhrBLhNQBNhMBrAAQBrAABMBMQBMBNABBrQgBBshMBMQhLBMhsAAQhsAAhMhMgABpDEQgyALgiAqQghArAAAzQABAzAhAqQAjAqAyAKQAdAGAegHQAegGAZgRQAqgdAPg1QAPg1gUgvQgVgugxgZQgigSgjAAQgOAAgPADgApfHyQhMhMABhsQgBhrBMhNQBOhMBrAAQBrAABMBMQBMBNAABrQAABshMBMQhLBMhsAAQhsAAhNhMgAm8DEQgyAKgiArQgiArAAAzQAAAzAjAqQAjAqAyAKQAdAGAegHQAegGAZgRQAqgdAPg1QAPg1gUgvQgVgugxgZQgigSgjAAQgOAAgPADgAGDE/IAAAAgAijE6IAAAAgARBmyIAAAAg");
	this.shape_3.setTransform(40.15,2.7714);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f().s("#000000").ss(5,1,1).p("Aoyz0QEeipFkAAQHCAAFSEMQA+AyA7A6QDSDTBdEDAUhoOQA0CwAADGQAAF9g4FXQhPHiimClQisCtlaAkQkZAelgg+QlyhCk9iaQkpiRjEjDQhWhXgKh7QgHhhApiUQA3ivAZhaQAtidAAhvQAAkuB5j8AwkrvQBZimCPiQQBphoB0hL");
	this.shape_4.setTransform(19.7984,3.1365);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AiiDQQg7AAgggHQgygIgggZQgngfgLgwQgFgXACguIACg1QAPAKAZALQAqAUAcAIIAWAGIAXAIQAOAFAbASIA0AfQAaAOAOAEQAQADAmgCIA3ABQAiABAVgDQAXgCAOgHIAFgCQAJgFAQgRIAXgXIBVhVIATgVQApgrBYhqIgCAPQgGAggOAmIgcBCIgkBOQgVAqgKAOQgWAhgmAcQgdAVgtAXQgmATgXAFQgPADgUACIgkAAg");
	this.shape_5.setTransform(20.3714,100.55);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FF0000").s().p("AgJCrQgcgCgVgHQgYgHgigWQgrgbgNgGQgSgJgwgPQgrgOgWgOIgQgKQgKgFgIgDQgGgBgFAAIAEhwQABg3AFggIASAbQAOAXAJAKQAiAkBNAQQArAKA7AFQAKAPAKAVIAWAsQAKATAIAMQAJAPAHAEQAHAFAGAAQAHABAIgCQANgDAFgKQAGgPgNgPQgPgPgGgJQgFgHgFgMIgHgUIgNgWQA5ADBEAAQA6AAAhgDQAygEAmgOQAXgJAqgXIgJAMQgoAxg4A6QgnApguAtQgiAjgYAIQgNAFgRADIgeACIglAAIgNAAg");
	this.shape_6.setTransform(16.825,88.7);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#000000").s().p("AksVaQhgAAgwgGQgygEgcgQQgbgOgmgqQgRgTgIgLQgMgRgGgQQgFgSAAgiQgBgYADhVIAIjCQADhMAHglQACgLADgFQABgMAIgFQAIgGAMAEQAJADAJAIQARAPAYApQAXAnASAPQATARAfAJQATAGAkAFQCoAXCPgIQA5gEAggKQAegKA8gjQA6giAigJIAPgDQAEgFAFgEQAIgFAJgBQAKAAAGAFQAKAJgCARQgCAKgIAUQgIAUgFAdIgJAyQgKAvgWA4QgOAigfBAQgVAtgNAVQg0BRhlA0QguAXgmAHQgbAFg2AAgApIRmQgCAtAFAXQAKAxAoAeQAgAZAxAJQAhAGA6AAICqACIAjAAQAUgBAPgEQAXgFAngTQAtgXAcgVQAlgcAXggQAKgOAVgrIAjhPIAchCQAOgmAGggIADgPQhZBqgoArIgUAVIhTBWIgXAYQgRAQgJAFIgEADQgOAGgXADQgWACgigBIg3AAQgmACgRgEQgOgDgagPIg0gfQgbgSgOgFIgWgIIgXgGQgcgIgpgUQgagMgOgKgAo5P5QAIACAKAGIAQAKQAWAOArAOQAwAPASAJQANAGArAbQAiAVAYAIQAVAHAcABIAOABIAlgBIAegCQARgCANgFQAYgJAigiQAugtAmgpQA4g7AogyIAJgLQgqAXgXAIQgmAOgxAFQghADg6AAQhEgBg6gDIANAXIAIAUQAFANAFAHQAGAIAPAQQANAPgGAOQgFALgNADQgIACgHgBQgHgBgHgEQgHgFgJgOQgIgMgKgTIgWgtQgKgVgKgPQg7gGgrgJQhNgQgiglQgJgKgOgWIgSgbQgFAggBA2IgEByIADAAIAIABgABsHOQgygJgigrQgigqgBgzQAAgzAhgqQAigrAygLQAygKAxAZQAwAZAVAvQAUAvgPA0QgPA1gpAdQgZASgeAGQgQADgPAAQgPAAgOgDgAm5HOQgygJgigrQgjgqgBgzQAAgzAigqQAigrAygLQAygKAxAZQAwAZAVAvQAUAvgPA0QgPA1gpAdQgZASgeAGQgQADgPAAQgPAAgOgDgAFCl5QgsguAAhDQAAhDAsgvQAsguA+AAQA+AAAsAuQAsAvAABDQAABDgsAuQgsAvg+AAQg+AAgsgvgAsnmNQgsgvAAhCQAAhDAsgvQAsguA+AAQA+AAAsAuQAsAvAABDQAABCgsAvQgsAvg+AAQg+AAgsgvgARAmVQgFgMABgPQACgNAEgPQAJgmAWguIA0hsQAXg0AlhxQAmhfA3gtQAtgkBIgSQAjgJBggNQCPgSCLghQgMgmgLgTQgRgegZgLQgSgJgmgBQifgEhiABQiMAChzANQkbAfjRBpQgbAOgQgBQgMgBgJgIQgJgJACgLQADgOAXgMQDThlDkglQCHgWCsgEQBqgCDLAGQAgABATADQAcAFASAOQAWAQAVArQAYAxAOAPIALAMQAGAIABAGQACAPgPALQgMAIgTAEQiuAoiwAYQhEAKggAIQg2APgiAcQggAcgYAwQgMAagXBBQgbBMgnBbQgaA7gwBpQgGANgHAFIgFABIgDAAQgJAAgGgLgA0Jo/QgTgBgNghIgYg/QgQgpgLgTQgLgWgbgqQgIgOgPghQgPgfgJgQQgXgogngnQgigkgogbQg7gphSgaQhAgUhagPQgUgDgMgHQgRgKABgPQAAgLAPgQQA+hCAnggQA9gxA8gPQAcgHAjgCQAXgCAoABQDmADDZALQA1ACAcAJQAPAFAUAKIAhASQAQAJAsATQAmASAVAMQBEAnAUA2QAEAMABAKQABALgEAJQgEAKgLAFQgLAFgJgGIgHgGQgCgDgCgFIgGgRQgMgogygdQgbgRg7gYIgtgZQgbgPgUgFQgXgHgqgCQjhgMjLgDQg4gBgeADQgwAFgkAPQgiAPgjAeQgYAUgkAnQBeAYAwAQQBNAaA4AiQBRA0A9BUQAeAqAkBFQARAgA0BoIAbA4QAIAQADAMQACAJgBAGQgBAMgIAJQgHAIgIABIgEAAg");
	this.shape_7.setTransform(40.0114,-9.9562);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FF66CC").s().p("AkjV3QlyhBk8iaQkqiRjEjEQhWhWgKh8QgGhgAoiVQA3ivAZhZQAtieAAhuQABkuB5j8QAIgCAHgHQAIgJABgMQAAgHgCgIQBZinCQiPQBohoB0hMQh0BMhoBoQiQCPhZCnQgDgMgHgRIgbg4Qg0hogRggQglhFgdgpQg+hVhRgzQg3gjhOgaQgvgQhegXQAjgnAYgVQAkgeAigPQAkgPAvgEQAegDA5AAQDKADDiANQApACAYAGQATAGAcAOIAtAZQA7AZAbAQQAyAeAMAnIAGASQACAEACADIAGAHQAKAFAKgFQALgEAFgKQAEgJgBgLQEeipFmAAQHAAAFSEMIACgDQAJAIAMABQAQABAbgOQDRhpEagfQB0gMCMgCQBigBCeAEQAnABASAIQAZALAQAeQAMAUAMAmQiLAhiQASQhfAMgjAJQhJASgsAlQg3AsgmBgQglBwgXA1Ig1BsQgWAugIAmQhdkEjTjSQg6g7g/gxQA/AxA6A7QDTDSBdEEQgEAOgCAOQgCAOAGAMQAGAOAMgCIAFgCQA0CxAADGQAAF9g5FXQhPHiimClQisCtlZAkQhcAKhiAAQjNAAjvgrgApaJVQgJAFAAALQgDAGgDALQgGAlgDBLIgJDDQgCBVABAYQgBAhAGATQAFAQANARQAHAKARATQAnArAaAOQAcAPAyAFQAwAFBhAAIBuAAQA2AAAbgFQAmgGAugYQBlgzA0hRQANgVAVgtQAehBAOgiQAXg3AKgvIAIgyQAGgeAIgTQAIgUACgKQACgSgKgIQgGgGgKABQgKAAgHAGQgFADgEAGIgQACQghAJg6AiQg9AkgeAJQgfAKg5AEQiPAJiogXQgkgGgUgGQgegJgTgQQgSgPgXgoQgYgpgRgPQgJgIgJgDIgIgBQgHAAgFAEgAiECmQAABsBLBMQBMBMBsAAQBsAABLhMQBMhMABhsQgBhrhMhMQhMhMhrAAQhrAAhNBMQhLBMAABrIAAAAgAqqChQgBBsBMBMQBNBMBsAAQBsAABLhMQBMhMAAhsQAAhrhMhMQhMhMhrAAQhrAAhOBMQhMBMABBrIAAAAgAFArbQgsAvAABCQAABDAsAuQAsAvA+AAQA/AAAsgvQAsguAAhDQAAhCgsgvQgsgvg/AAQg9AAgtAvgAsorvQgtAvABBCQgBBDAtAuQAsAvA9AAQA/AAArgvQAsguAAhDQAAhCgsgvQgrgvg/AAQg9AAgsAvgAg5FeQhLhMAAhsQAAhrBLhMQBNhMBrAAQBrAABMBMQBMBMABBrQgBBshMBMQhLBMhsAAQhsAAhMhMgABpArQgyALgiAqQghArAAAzQABAzAhAqQAjAqAyAKQAdAGAegHQAegGAZgRQAqgdAPg1QAPg1gUgvQgVgugxgZQgigSgjAAQgOAAgPADgApfFZQhMhMABhsQgBhrBMhMQBOhMBrAAQBrAABMBMQBMBMAABrQAABshMBMQhLBMhsAAQhsAAhNhMgAm8ArQgyAKgiArQgiArAAAzQAAAzAjAqQAjAqAyAKQAdAGAegHQAegGAZgRQAqgdAPg1QAPg1gUgvQgVgugxgZQgigSgjAAQgOAAgPADgAGDCmIAAAAgAijChIAAAAgARBpLIAAAAg");
	this.shape_8.setTransform(40.15,2.7579);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape,p:{y:-0.55}}]}).to({state:[{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape,p:{y:-15.85}}]},1).to({state:[{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape,p:{y:-15.85}}]},1).to({state:[{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape,p:{y:-0.55}}]},1).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-153.7,-146.9,387.4,296.3);


// stage content:
(lib.Nack_newhaiku = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {words:0,artwork:1};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	this.actionFrames = [0,1];
	// timeline functions:
	this.frame_0 = function() {
		this.stop();
		var root = this;
		stage.enableMouseOver();
		 
		this.toFrame02_btn.addEventListener("click",toFrame02);
		
		function toFrame02(){
			console.log("will go to frame 2");
			root.gotoAndStop("artwork");
		}
		
		this.line01_txt.addEventListener("click",changeLine01);
		
		function changeLine01(){
			console.log("will change line 1")
			root.line01_txt.text = line01;
		}
		
		var line01 = "The pig";
		
		this.line02_txt.addEventListener("click",changeLine02);
		
		function changeLine02(){
			console.log("will change line 2")
			root.line02_txt.text = line02;
		}
		
		var line02 = "Opens his mouth wide for the apple";
		
		this.line03_txt.addEventListener("click",changeLine03);
		
		function changeLine03(){
			console.log("and wins first place")
			root.line03_txt.text = line03;
		}
		
		var line03 = "Receives the gold medal";
	}
	this.frame_1 = function() {
		this.stop();
		var root = this;
		stage.enableMouseOver();
		 
		this.toFrame01_btn.addEventListener("click",toFrame01);
		
		function toFrame01(){
			console.log("will go to frame 1");
			root.gotoAndStop("words");
		}
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(1).call(this.frame_1).wait(1));

	// buttons
	this.toFrame02_btn = new lib.circlebutton();
	this.toFrame02_btn.name = "toFrame02_btn";
	this.toFrame02_btn.setTransform(751.7,513.35,0.8048,0.7344);
	new cjs.ButtonHelper(this.toFrame02_btn, 0, 1, 2, false, new lib.circlebutton(), 3);

	this.toFrame01_btn = new lib.circlebutton();
	this.toFrame01_btn.name = "toFrame01_btn";
	this.toFrame01_btn.setTransform(763.3,521,0.7007,0.6964);
	new cjs.ButtonHelper(this.toFrame01_btn, 0, 1, 2, false, new lib.circlebutton(), 3);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.toFrame02_btn}]}).to({state:[{t:this.toFrame01_btn}]},1).wait(1));

	// apple
	this.instance = new lib.Food();
	this.instance.setTransform(200.05,483.05,0.4205,0.3775,0,0,0,-17.7,4.8);
	this.instance._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1).to({_off:false},0).wait(1));

	// goldmedal
	this.instance_1 = new lib.Goldmedal();
	this.instance_1.setTransform(456.05,301.35,1,1,0,0,0,5,-148);
	this.instance_1._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(1).to({_off:false},0).wait(1));

	// text
	this.line03_txt = new cjs.Text("Line  3", "bold 40px 'Fira Mono'", "#323232");
	this.line03_txt.name = "line03_txt";
	this.line03_txt.textAlign = "center";
	this.line03_txt.lineHeight = 50;
	this.line03_txt.lineWidth = 359;
	this.line03_txt.parent = this;
	this.line03_txt.setTransform(470.1,370.1);

	this.line02_txt = new cjs.Text("Line  2", "bold 40px 'Fira Mono'", "#323232");
	this.line02_txt.name = "line02_txt";
	this.line02_txt.textAlign = "center";
	this.line02_txt.lineHeight = 50;
	this.line02_txt.lineWidth = 359;
	this.line02_txt.parent = this;
	this.line02_txt.setTransform(470.1,232.1);

	this.line01_txt = new cjs.Text("Line  1", "bold 40px 'Fira Mono'", "#323232");
	this.line01_txt.name = "line01_txt";
	this.line01_txt.textAlign = "center";
	this.line01_txt.lineHeight = 50;
	this.line01_txt.lineWidth = 359;
	this.line01_txt.parent = this;
	this.line01_txt.setTransform(470.1,99.05);

	this.instance_2 = new lib.CachedBmp_1();
	this.instance_2.setTransform(148,19.3,0.5,0.5);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.instance_2},{t:this.line01_txt},{t:this.line02_txt},{t:this.line03_txt}]}).to({state:[]},1).wait(1));

	// background
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#663300").ss(1,1,1).p("Ehetg72MC9bAAAMAAAB3tMi9bAAAg");
	this.shape.setTransform(462.1,345.125);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#66FFCC").s().p("EhetA73MAAAh3tMC9aAAAMAAAB3tg");
	this.shape_1.setTransform(462.1,345.125);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f().s("#000000").ss(5,1,1).p("EhZEg8KMCyJAAAMAAAB4VMiyJAAAg");
	this.shape_2.setTransform(480.125,313.1);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#00FF66").s().p("EhZEA8LMAAAh4VMCyJAAAMAAAB4Vg");
	this.shape_3.setTransform(480.125,313.1);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_1},{t:this.shape}]}).to({state:[{t:this.shape_3},{t:this.shape_2}]},1).wait(1));

	this._renderFirstFrame();

}).prototype = p = new lib.AnMovieClip();
p.nominalBounds = new cjs.Rectangle(335,245.5,734.3,483.70000000000005);
// library properties:
lib.properties = {
	id: '3334ACF74CED99499F69C88908A147B3',
	width: 960,
	height: 640,
	fps: 24,
	color: "#FFFFFF",
	opacity: 1.00,
	manifest: [
		{src:"images/Nack_newhaiku_atlas_1.png?1772496194588", id:"Nack_newhaiku_atlas_1"}
	],
	preloads: []
};



// bootstrap callback support:

(lib.Stage = function(canvas) {
	createjs.Stage.call(this, canvas);
}).prototype = p = new createjs.Stage();

p.setAutoPlay = function(autoPlay) {
	this.tickEnabled = autoPlay;
}
p.play = function() { this.tickEnabled = true; this.getChildAt(0).gotoAndPlay(this.getTimelinePosition()) }
p.stop = function(ms) { if(ms) this.seek(ms); this.tickEnabled = false; }
p.seek = function(ms) { this.tickEnabled = true; this.getChildAt(0).gotoAndStop(lib.properties.fps * ms / 1000); }
p.getDuration = function() { return this.getChildAt(0).totalFrames / lib.properties.fps * 1000; }

p.getTimelinePosition = function() { return this.getChildAt(0).currentFrame / lib.properties.fps * 1000; }

an.bootcompsLoaded = an.bootcompsLoaded || [];
if(!an.bootstrapListeners) {
	an.bootstrapListeners=[];
}

an.bootstrapCallback=function(fnCallback) {
	an.bootstrapListeners.push(fnCallback);
	if(an.bootcompsLoaded.length > 0) {
		for(var i=0; i<an.bootcompsLoaded.length; ++i) {
			fnCallback(an.bootcompsLoaded[i]);
		}
	}
};

an.compositions = an.compositions || {};
an.compositions['3334ACF74CED99499F69C88908A147B3'] = {
	getStage: function() { return exportRoot.stage; },
	getLibrary: function() { return lib; },
	getSpriteSheet: function() { return ss; },
	getImages: function() { return img; }
};

an.compositionLoaded = function(id) {
	an.bootcompsLoaded.push(id);
	for(var j=0; j<an.bootstrapListeners.length; j++) {
		an.bootstrapListeners[j](id);
	}
}

an.getComposition = function(id) {
	return an.compositions[id];
}


an.makeResponsive = function(isResp, respDim, isScale, scaleType, domContainers) {		
	var lastW, lastH, lastS=1;		
	window.addEventListener('resize', resizeCanvas);		
	resizeCanvas();		
	function resizeCanvas() {			
		var w = lib.properties.width, h = lib.properties.height;			
		var iw = window.innerWidth, ih=window.innerHeight;			
		var pRatio = window.devicePixelRatio || 1, xRatio=iw/w, yRatio=ih/h, sRatio=1;			
		if(isResp) {                
			if((respDim=='width'&&lastW==iw) || (respDim=='height'&&lastH==ih)) {                    
				sRatio = lastS;                
			}				
			else if(!isScale) {					
				if(iw<w || ih<h)						
					sRatio = Math.min(xRatio, yRatio);				
			}				
			else if(scaleType==1) {					
				sRatio = Math.min(xRatio, yRatio);				
			}				
			else if(scaleType==2) {					
				sRatio = Math.max(xRatio, yRatio);				
			}			
		}
		domContainers[0].width = w * pRatio * sRatio;			
		domContainers[0].height = h * pRatio * sRatio;
		domContainers.forEach(function(container) {				
			container.style.width = w * sRatio + 'px';				
			container.style.height = h * sRatio + 'px';			
		});
		stage.scaleX = pRatio*sRatio;			
		stage.scaleY = pRatio*sRatio;
		lastW = iw; lastH = ih; lastS = sRatio;            
		stage.tickOnUpdate = false;            
		stage.update();            
		stage.tickOnUpdate = true;		
	}
}
an.handleSoundStreamOnTick = function(event) {
	if(!event.paused){
		var stageChild = stage.getChildAt(0);
		if(!stageChild.paused || stageChild.ignorePause){
			stageChild.syncStreamSounds();
		}
	}
}
an.handleFilterCache = function(event) {
	if(!event.paused){
		var target = event.target;
		if(target){
			if(target.filterCacheList){
				for(var index = 0; index < target.filterCacheList.length ; index++){
					var cacheInst = target.filterCacheList[index];
					if((cacheInst.startFrame <= target.currentFrame) && (target.currentFrame <= cacheInst.endFrame)){
						cacheInst.instance.cache(cacheInst.x, cacheInst.y, cacheInst.w, cacheInst.h);
					}
				}
			}
		}
	}
}


})(createjs = createjs||{}, AdobeAn = AdobeAn||{});
var createjs, AdobeAn;